// <auto-generated />
namespace SmoONE.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddGestures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGestures));
        
        string IMigrationMetadata.Id
        {
            get { return "201710240738119_AddGestures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
